# ---- Metadata / tagging ----
variable "region" {
  description = "AWS region for Region A"
  type        = string
  default     = "ca-central-1"
}

variable "name_prefix" {
  description = "Name prefix for Region A resources (e.g. capstone-ca)"
  type        = string
  default     = "capstone-ca"
}

variable "project" {
  type    = string
  default = "aws-capstone-eks-multiregion"
}

variable "environment" {
  type    = string
  default = "dev"
}

variable "owner" {
  type    = string
  default = "vani"
}

variable "cost_center" {
  type    = string
  default = "cc-1001"
}

# ---- Networking ----
variable "vpc_cidr" {
  type    = string
  default = "10.0.0.0/16"
}

variable "azs" {
  description = "AZs to use (must match your subnets lists)"
  type        = list(string)
  default     = ["ca-central-1a", "ca-central-1b"]
}

variable "public_subnets" {
  type    = list(string)
  default = ["10.0.1.0/24", "10.0.2.0/24"]
}

variable "private_subnets" {
  type    = list(string)
  default = ["10.0.11.0/24", "10.0.12.0/24"]
}

# ---- EKS ----
variable "eks_node_types" {
  type    = list(string)
  default = ["t3.medium"]
}

variable "eks_desired" {
  type    = number
  default = 2
}

variable "eks_min" {
  type    = number
  default = 1
}

variable "eks_max" {
  type    = number
  default = 3
}

# ---- RDS ----
variable "db_username" {
  type    = string
  default = "appuser"
}

# db_password is generated by random_password + Secrets Manager in main.tf,
variable "db_password" {
  type      = string
  sensitive = true
  default   = "" 
}
